openapi: 3.0.1
info:
  title: monster-modron-monodrone
  x-cortex-tag: monster-modron-monodrone
  x-cortex-custom-metadata:
    alignment: neutral-good
    type: fey
    challenge_rating: 24
    legendary: false
    armor_class: 16
    hit_points: 105
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-modron-monodrone
      alias: github-token-test
